### ISSUE TITLE
Weird fonts on Firefox

### ISSUE THREAD

**Issue by g105b** [camomeui/camome#72]
Sidebar changes font to significantly different font when clicking a link:

![image](https://user-images.githubusercontent.com/358014/219378874-6d7f3c65-7590-4006-91a5-82209c2d3bcd.png)

This issue must be causing aligning issues on basic elements:

![image](https://user-images.githubusercontent.com/358014/219379043-cc33dd70-65d9-4d2e-8ff0-d9e9e3365c48.png)

I've never contributed on any React code, but would love to learn. If you could point me in the direction I'm happy to look at a solution to this, but I'm finding it a bit overwhelming to understand the codebase as a server side developer it's not my usual thing.

**Comment by sabigara** [comment]
Thank you for opening the issue!

Hmm, weird. Are you on Windows or Linux? Does the issue occur on Chrome or other browsers too?

They should look like these:

<img width="345" alt="Screenshot 2023-02-16 22 56 06" src="https://user-images.githubusercontent.com/41217985/219384335-534674fc-ce07-4741-8457-f009f3551afe.png">

<img width="263" alt="Screenshot 2023-02-16 22 55 51" src="https://user-images.githubusercontent.com/41217985/219384565-9880b906-95b4-4aa9-8980-321f48015c4c.png">

**Comment by g105b** [comment]
It looks OK in Chrome/Edge. I'm using Linux (Pop OS! 22.04), and this is the first time I've noticed anything strange with font rendering... but with it being a design framework the problem was more obvious to me, so maybe I've just not noticed other websites. I'm not a designer, but I could see this was wrong from a mile off.

**Comment by sabigara** [comment]
Thank you for the details. While I'm not sure what is the cause, just enabled a web font which would be also great for providing the same feeling across multiple OS anyway.

Can you try this preview deployment: https://camome-40c4lp1hv-rubik.vercel.app/

**Comment by g105b** [comment]
![image](https://user-images.githubusercontent.com/358014/219604708-7da16a32-e963-40c6-818e-e8a4eae7673a.png)

![image](https://user-images.githubusercontent.com/358014/219604768-0a421580-21fe-4d5a-879f-6fe3aca21779.png)

Looks great now in my Firefox!
