### ISSUE TITLE
Supported browsers?

### ISSUE THREAD

**Issue by mtripg6666tdr** [camomeui/camome#74]
I'm interested in this lightweight framework, but I found soon the website and the documentation site are completely broken for me.
![Screenshot_2023-02-17-18-06-00~2](https://user-images.githubusercontent.com/56076195/219602396-f02a7f32-2d3c-4dad-8cf3-cf1a909954d6.png)
I think this is caused because I'm using the browser that is a little old (due to the EOL OS version).
Compatibility is the important thing for production environment, so now my question is which browsers and versions are (or will be support in future)supported by camome-ui?

**Comment by sabigara** [comment]
Not yet decided what exact versions and browsers to support, but I don't think Camome will support versions older than the current latest releases.

**Comment by mtripg6666tdr** [comment]
ok thanks for your fast reply.
