### ISSUE TITLE
TextInput: add additional input types

### ISSUE THREAD

**Issue by ArthurClemens** [camomeui/camome#76]
I am missing type `date`, but in general a lot of [text input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types) are currently not supported by the component props:

- `color`
- `date`
- `datetime-local`
- `email`
- `month`
- `number`
- `tel`
- `time`
- `week`

**Comment by sabigara** [comment]
`TextInput` only accepts `"text" | "email" | "url" | "password" | "search"` and this type restriction is intentionally narrowed to only support "textual" types. But as you point out there are lots of missing input types. I'm planning to implement `color` and `date` but have not yet considered other types.

**Comment by ArthurClemens** [comment]
You could simply use `HTMLInputTypeAttribute` that is provided by `@types/react`.

**Comment by sabigara** [comment]
Closed by #87
